#!/bin/bash

source ../.zephyr-venv/bin/activate
pip install -r ../modules/hal/espressif/requirements.txt

export ESPRESSIF_TOOLCHAIN_PATH="${HOME}/.espressif/tools/xtensa-esp32-elf/esp-2022r1-RC1-11.2.0/xtensa-esp32-elf"
export PATH="${PATH}:${ESPRESSIF_TOOLCHAIN_PATH}/bin"
unset IDF_PATH
